[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = "/home/ubuntu/sublake/submodules/brc20shrew-rs/wasm-test-runner.sh"
rustflags = ["--cfg=getrandom_js"]

[env]
RUSTFLAGS = "--cfg=web_sys_unstable_apis --cfg=getrandom_js"
